# Generated by Django 6.0.5 on 2026-05-23 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tittle / Jina la nyumba')),
                ('description', models.TextField(verbose_name='Description/Maelezo')),
                ('county', models.CharField(max_length=100, verbose_name='County / Kaunti')),
                ('town', models.CharField(max_length=100, verbose_name='Town / Mji')),
                ('location', models.CharField(max_length=300, verbose_name='Exact location')),
                ('bedrooms', models.IntegerField(verbose_name='Bedrooms / Vyumba vya kulala')),
                ('bathrooms', models.IntegerField(verbose_name='Bathrooms / Bafu')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent per Month (Ksh)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
