# Generated by Django 6.0.5 on 2026-06-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='House Photo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(max_length=100, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tittle'),
        ),
        migrations.AlterField(
            model_name='property',
            name='town',
            field=models.CharField(max_length=100, verbose_name='Town'),
        ),
    ]
