# Generated by Django 6.0.5 on 2026-06-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='Property',
            new_name='property',
        ),
    ]
